# Generated by Django 6.0.7 on 2026-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "author"]},
        ),
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
